#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>

const char* ssid = "moto g45 - ThiruXD";  // Replace with your WiFi SSID
const char* password = "1234567890";  // Replace with your WiFi Password

ESP8266WebServer server(80);

void setup() {
  Serial.begin(9600);  // Communicate with Arduino
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("\nWiFi Connected!");

  // Web Page
  server.on("/", []() {
    server.send(200, "text/html", 
      "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Arduino Based Project By ThiruXD</title>\n"
"    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
"    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n"
"    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css\">\n"
"    <style>\n"
"        /* Minimal custom CSS */\n"
"        .toggle-checkbox:checked {\n"
"            @apply right-0 border-blue-500;\n"
"            right: 0;\n"
"            border-color: #3b82f6;\n"
"        }\n"
"        .toggle-checkbox:checked + .toggle-label {\n"
"            @apply bg-blue-500;\n"
"        }\n"
"        .swiper-pagination-bullet-active {\n"
"            @apply bg-blue-500;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body class=\"bg-white text-gray-800 font-sans antialiased\">\n"
"    <!-- Header -->\n"
"    <header class=\"fixed w-full bg-white shadow-sm z-50 transition-all duration-300\">\n"
"        <div class=\"container mx-auto px-6 py-4 flex justify-between items-center\">\n"
"            <a href=\"#\" class=\"text-2xl font-bold text-blue-600\">Arduino<span class=\"text-blue-400\">Project</span></a>\n"
"            <nav class=\"hidden md:flex space-x-8\">\n"
"                <a href=\"#home\" class=\"font-medium hover:text-blue-500 transition\">Home</a>\n"
"                <a href=\"#about\" class=\"font-medium hover:text-blue-500 transition\">About</a>\n"
"                <a href=\"#controller\" class=\"font-medium hover:text-blue-500 transition\">Controller</a>\n"
"                <a href=\"#components\" class=\"font-medium hover:text-blue-500 transition\">Components</a>\n"
"                <a href=\"#team\" class=\"font-medium hover:text-blue-500 transition\">Team</a>\n"
"            </nav>\n"
"            <button class=\"md:hidden text-2xl\" id=\"menu-toggle\">\n"
"                <i class=\"fas fa-bars\"></i>\n"
"            </button>\n"
"        </div>\n"
"        <!-- Mobile menu -->\n"
"        <div class=\"md:hidden hidden bg-white w-full py-4 px-6 shadow-md\" id=\"mobile-menu\">\n"
"            <div class=\"flex flex-col space-y-4\">\n"
"                <a href=\"#home\" class=\"font-medium hover:text-blue-500 transition\">Home</a>\n"
"                <a href=\"#about\" class=\"font-medium hover:text-blue-500 transition\">About</a>\n"
"                <a href=\"#controller\" class=\"font-medium hover:text-blue-500 transition\">Controller</a>\n"
"                <a href=\"#components\" class=\"font-medium hover:text-blue-500 transition\">Components</a>\n"
"                <a href=\"#team\" class=\"font-medium hover:text-blue-500 transition\">Team</a>\n"
"            </div>\n"
"        </div>\n"
"    </header>\n"
"\n"
"    <!-- Hero Section (Photo Removed) -->\n"
"    <section id=\"home\" class=\"min-h-screen flex items-center bg-gradient-to-br from-blue-50 to-white pt-20\">\n"
"        <div class=\"container mx-auto px-6 py-20 text-center max-w-3xl\">\n"
"            <h1 class=\"text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6\">Arduino Based <span class=\"text-blue-500\">Smart Remote</span> for Appliances</h1>\n"
"            <p class=\"text-lg text-gray-600 mb-8\">We build smart remote that control your electrical appliances. Our platform offers seamless integration. A part of the Final Year Project at P.S.V Polytechnic College</p>\n"
"            <div class=\"flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4\">\n"
"                <a href=\"https://github.com/ThiruXD/Arduino-Based-Project\" class=\"bg-blue-500 hover:bg-blue-600 text-white font-medium py-3 px-6 rounded-lg transition shadow-md hover:shadow-lg\">Source Code</a>\n"
"                <a href=\"#controller\" class=\"border-2 border-blue-500 text-blue-500 hover:bg-blue-50 font-medium py-3 px-6 rounded-lg transition\">Live Demo</a>\n"
"            </div>\n"
"        </div>\n"
"    </section>\n"
"\n"
"    <!-- About Section -->\n"
"    <section id=\"about\" class=\"py-20 bg-gray-50\">\n"
"        <div class=\"container mx-auto px-6\">\n"
"            <h2 class=\"text-3xl md:text-4xl font-bold text-center mb-16 relative pb-4\">\n"
"                Who We Are\n"
"                <span class=\"absolute bottom-0 left-1/2 transform -translate-x-1/2 w-16 h-1 bg-blue-500 rounded-full\"></span>\n"
"            </h2>\n"
"            <div class=\"flex flex-col lg:flex-row items-center gap-12\">\n"
"                <div class=\"hidden lg:block lg:w-1/2\">\n"
"                    <img src=\"https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\" alt=\"Our Team\" class=\"rounded-xl shadow-xl w-full\">\n"
"                </div>\n"
"                <div class=\"lg:w-1/2\">\n"
"                    <h3 class=\"text-2xl font-bold mb-4\">ECE students in P.S.V Polytechnic College</h3>\n"
"                    <p class=\"text-gray-600 mb-6\">Started in 2025, The forefront of IoT innovation, delivering cutting-edge solutions to enterprises and consumers alike.</p>\n"
"                    <p class=\"text-gray-600 mb-8\">Our team of students work collaboratively to create systems that are not just smart but intuitive and transformative.</p>\n"
"                    <div class=\"grid grid-cols-2 gap-4 mb-8\">\n"
"                        <div class=\"bg-white p-4 rounded-lg shadow-sm\">\n"
"                            <div class=\"text-blue-500 text-2xl mb-2\">\n"
"                                <i class=\"fas fa-microchip\"></i>\n"
"                            </div>\n"
"                            <h4 class=\"font-bold mb-1\">Hardware</h4>\n"
"                            <p class=\"text-sm text-gray-600\">Custom designed IoT nodes</p>\n"
"                        </div>\n"
"                        <div class=\"bg-white p-4 rounded-lg shadow-sm\">\n"
"                            <div class=\"text-blue-500 text-2xl mb-2\">\n"
"                                <i class=\"fas fa-code\"></i>\n"
"                            </div>\n"
"                            <h4 class=\"font-bold mb-1\">Software</h4>\n"
"                            <p class=\"text-sm text-gray-600\">Scalable C++/HTML infrastructure</p>\n"
"                        </div>\n"
"                    </div>\n"
"                    <a href=\"#team\" class=\"inline-block bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-6 rounded-lg transition shadow-md\">Meet Our Team</a>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </section>\n"
"\n"
"    <!-- Remote Controller Section -->\n"
"    <section id=\"controller\" class=\"py-20 bg-white\">\n"
"        <div class=\"container mx-auto px-6\">\n"
"            <h2 class=\"text-3xl md:text-4xl font-bold text-center mb-16 relative pb-4\">\n"
"                Device Controller\n"
"                <span class=\"absolute bottom-0 left-1/2 transform -translate-x-1/2 w-16 h-1 bg-blue-500 rounded-full\"></span>\n"
"            </h2>\n"
"            <div class=\"max-w-md mx-auto bg-white rounded-xl shadow-lg overflow-hidden p-8\">\n"
"                <div class=\"text-center mb-8\">\n"
"                    <div class=\"w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4\">\n"
"                        <i class=\"fas fa-sliders-h text-blue-500 text-2xl\"></i>\n"
"                    </div>\n"
"                    <h3 class=\"text-xl font-bold mb-2\">Remote Device Management</h3>\n"
"                    <p class=\"text-gray-600\">Control your connected devices from anywhere</p>\n"
"                </div>\n"
"                <div class=\"space-y-6\">\n"
"                    <div>\n"
"                        <label class=\"block text-gray-700 mb-2\">Display Your Text</label>\n"
"                        <input type=\"text\" id='lcdText' placeholder=\"Enter Any Text\" class=\"w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition\">\n"
"                    </div>\n"
"                    <div class=\"space-y-4\">\n"
"                        <div class=\"flex items-center justify-between\">\n"
"                            <span class=\"font-medium\">Fan</span>\n"
"                            <div class=\"relative inline-block w-12 mr-2 align-middle select-none\">\n"
"                                <input type=\"checkbox\" onchange=\"fetch('/toggle?device=fan')\" name=\"power\" id=\"power\" class=\"toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer\"/>\n"
"                                <label for=\"power\" class=\"toggle-label block overflow-hidden h-6 rounded-full bg-gray-300 cursor-pointer\"></label>\n"
"                            </div>\n"
"                        </div>\n"
"                        <div class=\"flex items-center justify-between\">\n"
"                            <span class=\"font-medium\">Light</span>\n"
"                            <div class=\"relative inline-block w-12 mr-2 align-middle select-none\">\n"
"                                <input type=\"checkbox\" onchange=\"fetch('/toggle?device=light')\" name=\"auto\" id=\"auto\" class=\"toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer\"/>\n"
"                                <label for=\"auto\" class=\"toggle-label block overflow-hidden h-6 rounded-full bg-gray-300 cursor-pointer\"></label>\n"
"                            </div>\n"
"                        </div>\n"
"                    </div>\n"
"                    <button onclick=\"fetch('/display?text='+document.getElementById('lcdText').value)\" class=\"w-full bg-blue-500 hover:bg-blue-600 text-white font-medium py-3 px-6 rounded-lg transition shadow-md\">Display It...</button>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </section>\n"
"\n"
"    <!-- Components Slider -->\n"
"    <section id=\"components\" class=\"py-20 bg-gray-50\">\n"
"        <div class=\"container mx-auto px-6\">\n"
"            <h2 class=\"text-3xl md:text-4xl font-bold text-center mb-16 relative pb-4\">\n"
"                Our Components\n"
"                <span class=\"absolute bottom-0 left-1/2 transform -translate-x-1/2 w-16 h-1 bg-blue-500 rounded-full\"></span>\n"
"            </h2>\n"
"            <div class=\"swiper\">\n"
"                <div class=\"swiper-wrapper pb-12\">\n"
"                    <!-- Component 1 -->\n"
"                    <div class=\"swiper-slide\">\n"
"                        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition transform hover:-translate-y-2\">\n"
"                            <div class=\"h-48 bg-blue-50 overflow-hidden\">\n"
"                                <img src=\"https://media.hackerearth.com/blog/wp-content/uploads/2017/02/Blog-Featured-Image.png\" alt=\"Smart Sensor\" class=\"w-full h-full object-cover object-center\">\n"
"                            </div>\n"
"                            <div class=\"p-6\">\n"
"                                <h3 class=\"text-xl font-bold mb-2\">Arduino UNO</h3>\n"
"                                <p class=\"text-gray-600 mb-4\">Arduino UNO is a microcontroller board based on the ATmega328P.</p>\n"
"                                <a href=\"https://docs.arduino.cc/hardware/uno-rev3/\" class=\"text-blue-500 font-medium inline-flex items-center\">\n"
"                                    Learn more <i class=\"fas fa-arrow-right ml-2\"></i>\n"
"                                </a>\n"
"                            </div>\n"
"                        </div>\n"
"                    </div>\n"
"                    <!-- Component 2 -->\n"
"                    <div class=\"swiper-slide\">\n"
"                        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition transform hover:-translate-y-2\">\n"
"                            <div class=\"h-48 bg-blue-50 overflow-hidden\">\n"
"                                <img src=\"https://www.electronicwings.com/storage/PlatformSection/TopicContent/211/description/esp8266.jpg\" alt=\"Smart Sensor\" class=\"w-full h-full object-cover object-center\">\n"
"                            </div>\n"
"                            <div class=\"p-6\">\n"
"                                <h3 class=\"text-xl font-bold mb-2\">ESP8266-01 Module</h3>\n"
"                                <p class=\"text-gray-600 mb-4\">The ESP8266-01 is an arduino module with built-in TCP/IP networking software.</p>\n"
"                                <a href=\"https://www.instructables.com/Getting-Started-With-the-ESP8266-ESP-01/\" class=\"text-blue-500 font-medium inline-flex items-center\">\n"
"                                    Learn more <i class=\"fas fa-arrow-right ml-2\"></i>\n"
"                                </a>\n"
"                            </div>\n"
"                        </div>\n"
"                    </div>\n"
"                    <!-- Component 3 -->\n"
"                    <div class=\"swiper-slide\">\n"
"                        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition transform hover:-translate-y-2\">\n"
"                            <div class=\"h-48 bg-blue-50 overflow-hidden\">\n"
"                                <img src=\"https://5.imimg.com/data5/SELLER/Default/2023/6/317207953/WN/QJ/LB/41932583/12-volt-2-channel-arduino-relay.jpg\" alt=\"Smart Sensor\" class=\"w-full h-full object-cover object-center\">\n"
"                            </div>\n"
"                            <div class=\"p-6\">\n"
"                                <h3 class=\"text-xl font-bold mb-2\">2-CHL Relay Module</h3>\n"
"                                <p class=\"text-gray-600 mb-4\">It designed to allow Arduino to control two high-powered devices.</p>\n"
"                                <a href=\"https://lastminuteengineers.com/two-channel-relay-module-arduino-tutorial/\" class=\"text-blue-500 font-medium inline-flex items-center\">\n"
"                                    Learn more <i class=\"fas fa-arrow-right ml-2\"></i>\n"
"                                </a>\n"
"                            </div>\n"
"                        </div>\n"
"                    </div>\n"
"                    <!-- Component 4 -->\n"
"                    <div class=\"swiper-slide\">\n"
"                        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition transform hover:-translate-y-2\">\n"
"                            <div class=\"h-48 bg-blue-50 overflow-hidden\">\n"
"                                <img src=\"https://www.sunfounder.com/cdn/shop/products/62520001-01_1200x.jpg?v=1601462322\" alt=\"Smart Sensor\" class=\"w-full h-full object-cover object-center\">\n"
"                            </div>\n"
"                            <div class=\"p-6\">\n"
"                                <h3 class=\"text-xl font-bold mb-2\">Liquid Crystal Displays (LCD)</h3>\n"
"                                <p class=\"text-gray-600 mb-4\">Customizable text with ESP8266-01 web page.</p>\n"
"                                <a href=\"https://docs.arduino.cc/learn/electronics/lcd-displays/\" class=\"text-blue-500 font-medium inline-flex items-center\">\n"
"                                    Learn more <i class=\"fas fa-arrow-right ml-2\"></i>\n"
"                                </a>\n"
"                            </div>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"swiper-pagination\"></div>\n"
"            </div>\n"
"        </div>\n"
"    </section>\n"
"\n"
"<!-- Circuit Block Diagram -->\n"
"<section class=\"min-h-screen bg-white-90 text-black flex flex-col items-center justify-center px-4 pt-4\">\n"
"  <h2 class=\"text-3xl md:text-4xl font-bold text-center mb-16 relative pb-4\">\n"
"                Circuit Diagram\n"
"                <span class=\"absolute bottom-0 left-1/2 transform -translate-x-1/2 w-16 h-1 bg-blue-500 rounded-full\"></span>\n"
"            </h2>\n"
"  <div class=\"w-full max-w-6xl\">\n"
"    <img src=\"https://i.ibb.co/M5DbfcZC/circuit-image.png\" alt=\"Circuit Diagram\" class=\"w-full h-auto\" />\n"
"  </div>\n"
"</section>\n"
"\n"
"<!-- Team Section -->\n"
"<section id=\"team\" class=\"py-20 bg-white\">\n"
"    <div class=\"container mx-auto px-4 sm:px-6 lg:px-8\">\n"
"      <h2 class=\"text-2xl sm:text-3xl md:text-4xl font-bold text-center mb-12 relative pb-4\">\n"
"        Our Team\n"
"        <span class=\"absolute bottom-0 left-1/2 transform -translate-x-1/2 w-16 h-1 bg-blue-500 rounded-full\"></span>\n"
"      </h2>\n"
"  \n"
"      <div class=\"grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6\">\n"
"  \n"
"        <!-- Team Member 1 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/F4YHM67R/photo-2021-02-10-14-50-54.jpg\" alt=\"Mr.S.Karthikeyan\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">Mr.S.Karthikeyan</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">HOD / Guide</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"#\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 2 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/wZg95VVs/Whats-App-Image-2025-04-18-at-00-14-35-2357f774.jpg\" alt=\"A.Thiruselvan\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">A.Thiruselvan</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Project Manager / Backend Developer</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://github.com/thiruXD/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-github text-lg\"></i></a>\n"
"              <a href=\"https://x.com/ThiruXD\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-twitter text-lg\"></i></a>\n"
"              <a href=\"https://www.linkedin.com/in/thiruxd/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-linkedin text-lg\"></i></a>\n"
"              <a href=\"https://thiruxd-me.vercel.app/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fa fa-chain-broken text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 3 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/ch2qHBx1/Whats-App-Image-2025-02-12-at-19-59-50-5188b84e.jpg\" alt=\"J.Rajapriyan\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">J.Rajapriyan</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Testing / Debugging Manager</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://www.instagram.com/red_lover_kd_r_s/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-instagram text-lg\"></i></a>\n"
"              <a href=\"mailto:rajapriyan729@gmail.com\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 4 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/dsw3YvGc/Screenshot-2025-04-18-010751.png\" alt=\"M.Manikandan\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">M.Manikandan</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Hardware Engineer</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://www.instagram.com/mani__solo__king__143/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-instagram text-lg\"></i></a>\n"
"              <a href=\"mailto:villanmani9095@gmail.com\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 5 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/d0KLX12t/Whats-App-Image-2025-03-07-at-20-36-01-e5d24850.jpg\" alt=\"M.Dinesh\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">M.Dinesh</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Assistant Documentation Manager</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://www.instagram.com/kd_dinesh_53/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-instagram text-lg\"></i></a>\n"
"              <a href=\"mailto:kddineshmadhu143@gmail.com\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 6 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/bj3jwyp3/photo-2025-04-18-00-43-33.jpg\" alt=\"D.Kumaresan\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">D.Kumaresan</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Web UI/UX Designer</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://www.instagram.com/__kumarez__/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-instagram text-lg\"></i></a>\n"
"              <a href=\"mailto:kumaresanin222@gmail.com\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"        <!-- Team Member 7 -->\n"
"        <div class=\"bg-white rounded-xl overflow-hidden shadow-md hover:shadow-lg transition-transform transform hover:-translate-y-2\">\n"
"          <div class=\"aspect-square bg-blue-50 overflow-hidden\">\n"
"            <img src=\"https://i.ibb.co/Rkr3LwVf/Whats-App-Image-2025-04-18-at-00-58-59-56efd85f.jpg\" alt=\"M.Kishore\" class=\"w-full h-full object-cover object-center\">\n"
"          </div>\n"
"          <div class=\"p-4 sm:p-5 text-center\">\n"
"            <h3 class=\"text-base sm:text-lg font-bold leading-tight mb-1 break-words\">M.Kishore</h3>\n"
"            <p class=\"text-blue-500 text-sm sm:text-base font-medium mb-3 break-words\">Report/Documentation Manager</p>\n"
"            <div class=\"flex justify-center space-x-3\">\n"
"              <a href=\"https://www.instagram.com/tom_jerry_kr/\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fab fa-instagram text-lg\"></i></a>\n"
"              <a href=\"mailto:mkishore274@gmail.com\" class=\"text-gray-500 hover:text-blue-500\"><i class=\"fas fa-envelope text-lg\"></i></a>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"  \n"
"      </div>\n"
"    </div>\n"
"  </section>\n"
"  \n"
"\n"
"\n"
"<h2>Smart Remote</h2>"
      "<button onclick=\"fetch('/toggle?device=fan')\">Fan ON/OFF</button>"
      "<button onclick=\"fetch('/toggle?device=light')\">Light ON/OFF</button><br><br>"
      "<input type='text' id='lcdText' placeholder='Enter text'>"
      "<button onclick=\"fetch('/display?text='+document.getElementById('lcdText').value)\">Send to LCD</button>"
      
"    <!-- Footer -->\n"
"    <footer class=\"bg-gray-900 text-white py-12\">\n"
"        <div class=\"container mx-auto px-6\">\n"
"            <div class=\"flex flex-col md:flex-row justify-between items-center\">\n"
"                <div class=\"mb-6 md:mb-0\">\n"
"                    <a href=\"#\" class=\"text-2xl font-bold text-white\">Arduino<span class=\"text-blue-400\">Project</span></a>\n"
"                    <p class=\"text-gray-400 mt-2\">Innovating the connected future</p>\n"
"                </div>\n"
"                <div class=\"flex space-x-6\">\n"
"                    <a href=\"https://x.com/ThiruXD\" class=\"text-gray-400 hover:text-white transition\"><i class=\"fab fa-twitter\"></i></a>\n"
"                    <a href=\"https://www.linkedin.com/in/thiruxd/\" class=\"text-gray-400 hover:text-white transition\"><i class=\"fab fa-linkedin-in\"></i></a>\n"
"                    <a href=\"https://github.com/ThiruXD/Arduino-Based-Project\" class=\"text-gray-400 hover:text-white transition\"><i class=\"fab fa-github\"></i></a>\n"
"                </div>\n"
"            </div>\n"
"            <div class=\"border-t border-gray-800 mt-8 pt-8 flex flex-col md:flex-row justify-between items-center\">\n"
"                <p class=\"text-gray-400 text-sm mb-4 md:mb-0\">© 2025 ThiruXD. All rights reserved.</p>\n"
"                <div class=\"flex space-x-6\">\n"
"                    <a href=\"https://github.com/ThiruXD/Arduino-Based-Project\" class=\"text-gray-400 hover:text-white text-sm transition\">Source Code</a>\n"
"                    <a href=\"https://en.wikipedia.org/wiki/International_piracy_law\" class=\"text-gray-400 hover:text-white text-sm transition\">Privacy Policy</a>\n"
"                    <a href=\"https://x.com/ThiruXD\" class=\"text-gray-400 hover:text-white text-sm transition\">Contact Us</a>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </footer>\n"
"\n"
"    <!-- Scripts -->\n"
"    <script src=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js\"></script>\n"
"    <script>function fetch(url){var x=new XMLHttpRequest();x.open('GET',url,true);x.send();}</script>\n"
"    <script>\n"
"        // Mobile menu toggle\n"
"        document.getElementById('menu-toggle').addEventListener('click', function() {\n"
"            document.getElementById('mobile-menu').classList.toggle('hidden');\n"
"        });\n"
"\n"
"        // Header scroll effect\n"
"        window.addEventListener('scroll', function() {\n"
"            const header = document.querySelector('header');\n"
"            if (window.scrollY > 50) {\n"
"                header.classList.add('shadow-lg');\n"
"                header.classList.add('py-2');\n"
"            } else {\n"
"                header.classList.remove('shadow-lg');\n"
"                header.classList.remove('py-2');\n"
"            }\n"
"        });\n"
"\n"
"        // Initialize Swiper\n"
"        new Swiper('.swiper', {\n"
"            slidesPerView: 1,\n"
"            spaceBetween: 20,\n"
"            pagination: {\n"
"                el: '.swiper-pagination',\n"
"                clickable: true,\n"
"            },\n"
"            breakpoints: {\n"
"                640: {\n"
"                    slidesPerView: 2,\n"
"                },\n"
"                1024: {\n"
"                    slidesPerView: 3,\n"
"                }\n"
"            }\n"
"        });\n"
"    </script>\n"
"</body>\n"
"</html>"
    );
  });

  server.on("/toggle", []() {
    String device = server.arg("device");
    if (device == "fan") Serial.println("FAN_TOGGLE");
    else if (device == "light") Serial.println("LIGHT_TOGGLE");
    server.send(200, "text/plain", "OK");
  });

  server.on("/display", []() {
    String text = server.arg("text");
    Serial.println("LCD:" + text);
    server.send(200, "text/plain", "OK");
  });

  server.begin();
}

void loop() {
  server.handleClient();
}
